name: Terraform CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      ENV: dev  # or staging/prod

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2  # match your local version

      # 4. Terraform Init
      - name: Terraform Init
        working-directory: ./environments/${{ env.ENV }}
        run: terraform init -backend-config="bucket=my-terraform-state-bucket-hachathon" -backend-config="key=${{ env.ENV }}/terraform.tfstate" -backend-config="region=${{ env.AWS_REGION }}"

      # 5. Terraform Plan
      - name: Terraform Plan
        working-directory: ./environments/${{ env.ENV }}
        run: terraform plan -out=tfplan

      # 6. Terraform Apply (optional, only on main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./environments/${{ env.ENV }}
        run: terraform apply -auto-approve tfplan
